dist: trusty
sudo: false
language: node_js
node_js: 10
cache:
  yarn: true
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
jobs:
  include:
  - stage: prepare cache
    script: true
  - stage: test
    script: npm test
stages:
  - prepare cache
  - test
notifications:
  slack: harmonizly:FiQyIOat1SVdXTCcZAjaGwq4
